### ISSUE TITLE
ruamel-yaml interfering with install on windows in anaconda

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#1042]
Hi all,

When re-installing anaconda/cobrapy on Windows, I ran into an issue with a package called ruamel-yaml. When I attempt to install cobrapy with pip.exe install cobra, I get this error message:

```
Installing collected packages: python-libsbml, sniffio, h11, httpcore, rfc3986, httpx, depinfo, swiglpk, pydantic, commonmark, rich, ruamel.yaml.clib, ruamel.yaml, diskcache, importlib-resources, appdirs, optlang, cobra
  Attempting uninstall: ruamel.yaml
    Found existing installation: ruamel-yaml 0.15.87
ERROR: Cannot uninstall 'ruamel-yaml'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
Other anaconda users have had similar issues with this package before: https://github.com/pypa/pip/issues/8789 and https://github.com/ContinuumIO/anaconda-issues/issues/12231

Anyone have any idea how I can work around this? Deleting the package directory and retrying install of cobrapy does nothing.

All the best,
Leno
(copied from discussion here: https://groups.google.com/g/cobra-pie/c/OWQAOve8qoQ)

**Comment by matthiaskoenig** [comment]
cobrapy requires at least 
```
ruamel.yaml ~=0.16
```
but you anaconda version of the dependency is too low. Could you try to update anaconda to the latest version which could include a newer dependency.

**Comment by cdiener** [comment]
Hopefully this is now fixed with the pure conda cobrapy package. Ergo this should not happen when using `conda install -c conda-forge cobra`.

**Comment by danielriosgarza** [comment]
Problem is not solved. 
 conda install -c conda-forge cobra                                                                                                                                        Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
